[package]
name = "goldfish"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
config = "0.15.7"
env_logger = "0.11.6"
log = "0.4.25"
nom = "8.0.0"
serde = { version = "1.0.217", features = ["std", "derive", "serde_derive"]}
tokio = { version = "1.43", features = ["full"] }

[dev-dependencies]
criterion = { version = "0.8", features = ["cargo_bench_support", "html_reports"] }

[[bench]]
name = "benchmarks"
harness = false

